# Generated by Django 4.0.3 on 2022-04-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_reset_password_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_email_verified',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
