apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-sync # The name of the SecretProviderClass to reference in the app manifest
  namespace: rdbw-dev
spec:
  provider: azure
  parameters:
    keyvaultName: mncfuivguic87cf7yu53cf8 # The name of the Azure Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "a6e52a5f-cb2a-4e62-b38c-041e6dae686a"  # <<<<This is where the $spClientId goes
    cloudName: "" # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: DJANGO-SENDER-EMAIL
          objectType: secret
          objectVersion: ""
        - |
          objectName: DJANGO-EMAIL-HOST-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: DJANGO-EMAIL-HOST-PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: df292b52-498a-400f-803d-5633e46b1759  # the tenant ID containing the Azure Key Vault instance