apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-sync # The name of the SecretProviderClass to reference in the app manifest
  namespace: rdbw-prod
spec:
  provider: azure
  parameters:
    keyvaultName: pxudfhe7vcyhgjwuibjqwu23 # The name of the Azure Key Vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "ecb5a5c1-5295-440a-932b-1d945a49fbac"  # <<<<This is where the $spClientId goes
    cloudName: "" # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: DJANGO-SENDER-EMAIL
          objectType: secret
          objectVersion: ""
        - |
          objectName: DJANGO-EMAIL-HOST-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: DJANGO-EMAIL-HOST-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: POSTGRESQL-PASSWORD
          objectType: secret
          objectVersion: ""
    tenantId: df292b52-498a-400f-803d-5633e46b1759  # the tenant ID containing the Azure Key Vault instance